---
name: kjumpingcube
version: 17.08.1
summary: simple tactical game
description: |-
 KJumpingcube is a simple tactical game for one or two players, played on a
 grid of numbered squares.  Each turn, players compete for control of the board
 by capturing or adding to one square.
confinement: strict
grade: stable
apps:
    kexi:
        command: kf5-launch kjumpingcube
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kexi:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkf5kdegames-dev
        - libkf5kdelibs4support-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kjumpingcube-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
